# Generated by Django 6.0.4 on 2026-04-22 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_catch_user_order_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='catch',
            constraint=models.UniqueConstraint(fields=('user', 'location'), name='unique_user_location_catch'),
        ),
    ]
