# Generated by Django 6.0.4 on 2026-04-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_badge_location_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='icon',
        ),
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
    ]
